version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql

  flask:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      FLASK_APP: myproject.py
      FLASK_RUN_HOST: 0.0.0.0
      DATABASE_URI: mysql+pymysql://user:user_password@db/flaskapp
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask

volumes:
  db_data:

